name: slo

on:
  pull_request:
    branches:
      - master
      - release-*
  workflow_dispatch:
    inputs:
      github_pull_request_number:
        required: true
      slo_workload_duration_seconds:
        default: '600'
        required: false
      slo_workload_read_max_rps:
        default: '1000'
        required: false
      slo_workload_write_max_rps:
        default: '100'
        required: false

jobs:
  ydb-slo-action-init:
    if: (!contains(github.event.pull_request.labels.*.name, 'no slo'))

    name: Run YDB SLO Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sdk:
          - id: database_sql
            name: database-sql
            path: ./database/sql
            label: database/sql
          - id: native_query
            name: native-query
            path: ./native/query
            label: native/query
          - id: native_table
            name: native-table
            path: ./native/table
            label: native/table
          - id: gorm
            name: gorm
            path: ./gorm
            label: gorm
          - id: xorm
            name: xorm
            path: ./xorm
            label: xorm

    concurrency:
      group: slo-${{ github.ref }}-${{matrix.sdk.name}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
          cache: true

      - name: Build workload
        run: |
          cd ./tests/slo
          go build -o .bin/${{matrix.sdk.id}}_linux_amd64 -ldflags "-X \"main.ref=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}\" -X \"main.label=${{matrix.sdk.label}}\" -X \"main.jobName=${{matrix.sdk.name}}\"" ${{matrix.sdk.path}}
          chmod +x .bin/${{matrix.sdk.id}}_linux_amd64

      - name: Inititialize YDB SLO
        uses: ydb-platform/ydb-slo-action/init@main
        with:
          github_pull_request_number: ${{ github.event.inputs.github_pull_request_number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sdk_name: ${{ matrix.sdk.name }}

      - name: Run SLO Tests
        run: |
          ./tests/slo/.bin/${{matrix.sdk.id}}_linux_amd64 create grpc://localhost:2135 /Root/testdb
          ./tests/slo/.bin/${{matrix.sdk.id}}_linux_amd64 run grpc://localhost:2135 /Root/testdb -prom-pgw localhost:9091 -report-period 500 -time ${{inputs.slo_workload_duration_seconds}} -read-rps ${{inputs.slo_workload_read_max_rps}} -write-rps ${{inputs.slo_workload_write_max_rps}}
          ./tests/slo/.bin/${{matrix.sdk.id}}_linux_amd64 cleanup grpc://localhost:2135 /Root/testdb
